### ISSUE TITLE
Reference for the material design icons used 

### ISSUE THREAD

**Issue by davetao** [tuckerconnelly/carbon-ui#19]
Hi.

I am having some trouble trying to find what icons are available to use. I have tried basic arrow_back / arrow_left options and it is coming up blank

Only some icons appear. Do you have any instructions on how it works?

- Edit I am using android

**Comment by tuckerconnelly** [comment]
Hey Dave, stoked you're using carbon-ui

I've got some examples here that work on Android for me: https://github.com/tuckerconnelly/react-stack-nav-examples

I'd make super sure you have the material-icons font in your assets/fonts folder, like it is here: https://github.com/tuckerconnelly/react-stack-nav-examples/tree/master/Drawer/android/app/src/main/assets/fonts

Lemme know how it goes

**Comment by davetao** [comment]
Hi.

So it looks like the icons just dont appear on the genymotion emulator for some odd reason. 

Thanks for the test project
