### ISSUE TITLE
How to use Breakpoints?

### ISSUE THREAD

**Issue by remon-georgy** [tuckerconnelly/carbon-ui#22]
I get a warning while using Breakpoints, I guess I don't know how to use them properly:

```
import React, { Component } from 'react';
import { Text } from 'react-native';
import { Breakpoints } from 'carbon-ui'

const styles = {
  base: {
    fontSize: 12,
    [Breakpoints.xl]: {
      // Font size should be 24 on Desktop.
      fontSize: 24,
    }
  }
}

class App extends Component {
  render() {
    return (
      <Text style={styles.base}>
        Clockworks
      </Text>
    );
  }
}

export default App;
```
Gives the warning:
```
Warning: Unsupported style property @media (min-width: 1600px). Did you mean @media (minWidth: 1600px)? Check the render method of `Text`.
```
Any clues?

**Comment by tuckerconnelly** [comment]
Use css prop instead of style 🙂

**Comment by remon-georgy** [comment]
Thanks for your quick response @tuckerconnelly!

I confirm that changing style prop to 'css' silents the warning. However, the property which was applying properly as a style, doesn't seem to apply anymore, i.e Text component now has default inherited font-size (16px) instead of desktop size (24px) or even the default one (12px).

**Comment by tuckerconnelly** [comment]
Ahh, need the Uranium HOC around App. Check uranium docs

**Comment by remon-georgy** [comment]
Nice! wrapping App with Uranium fixed it. Wasn't obvious in Carbon-ui docs if you ask me ;).

Closing this issue.
