### ISSUE TITLE
ReactInjection Missing from React 15.4.1 Install

### ISSUE THREAD

**Issue by mattferrin** [tuckerconnelly/carbon-ui#3]
I'm just trying to get up and running and noticed React 15.3 contained a lib dependency that 15.4 doesn't.

![simulator screen shot dec 9 2016 4 05 03 pm](https://cloud.githubusercontent.com/assets/2746787/21067655/f81de9b2-be29-11e6-97ae-8606c762da77.png)

**Comment by tuckerconnelly** [comment]
Ah yeah, need to add react to the peer dependencies. Make sure react 15.3.2 is installed:

```
npm -S i react@15.3.2
```

And in package.json remove the caret: `"react": "15.3.2"`

---

Waiting on https://github.com/tuckerconnelly/carbon-ui/issues/1 and https://github.com/necolas/react-native-web/pull/255 for 15.4 support :)

**Comment by mattferrin** [comment]
We'll need to know both the latest React and React Native versions that work. Trying to find the correct React Native version has me running into an issue that was fixed in later versions of React [https://github.com/facebook/react-native/issues/4949](https://github.com/facebook/react-native/issues/4949).

**Comment by tuckerconnelly** [comment]
Ah gotcha, I think react-native 0.37.0 is the latest that works.

BTW, two example projects using carbon-ui over here if you need them: https://github.com/tuckerconnelly/react-stack-nav-examples

**Comment by remon-georgy** [comment]
Hurray! react-native-web is now compatible with latest React :). Shall we start by bringing tuckerconnelly/react-native-web to latest RNW version?

**Comment by tuckerconnelly** [comment]
Okay yup, this is good to go :) Should work with the latest react and react-native now.
