### ISSUE TITLE
Unknown 'web' Module with Relative Path

### ISSUE THREAD

**Issue by mattferrin** [tuckerconnelly/carbon-ui#4]
Unable to resolve 'web' module.

![simulator screen shot dec 9 2016 5 04 23 pm](https://cloud.githubusercontent.com/assets/2746787/21068883/29381894-be32-11e6-9892-ff997eaa4917.png)

**Comment by tuckerconnelly** [comment]
Add index.js to `./web` like here: https://github.com/tuckerconnelly/react-stack-nav-examples/blob/master/Drawer/web/index.js

This will go away once we get https://github.com/tuckerconnelly/carbon-ui/issues/1 done

Thanks a bunch btw for going through the setup and filing these issues :) Will use all of this to smooth out the process as much as possible

**Comment by remon-georgy** [comment]
Yeah, besides carbon-ui installation, I had to follow tuckerconnelly/react-native-web installation steps as well, which mentions adding index.js. Perhaps we can be a bit redundant by copying those instructions to carbon-ui too.

**Comment by mattferrin** [comment]
And I'm using `carbon-ui` as a 'polyfill' for `material-ui`, so it seemed unnecessary for me to need to do this web step entirely since I was executing React Native code. Just feedback.

**Comment by tuckerconnelly** [comment]
It should work out-of-the-box with just React Native :) Try deleting all the web stuff and lemme know how it blows up.

**Comment by tuckerconnelly** [comment]
Ok, this is fixed on `tuckerconnelly/react-native-web`. Gonna track react-native-web stuff on https://github.com/tuckerconnelly/carbon-ui/issues/1
