### ISSUE TITLE
Launches Fine from Xcode not from Console (iOS Only)

### ISSUE THREAD

**Issue by mattferrin** [tuckerconnelly/carbon-ui#5]
This is just a placeholder to see if anyone else experiences an issue where they `react-native run-ios` and the app crashes upon launch.

**Comment by tuckerconnelly** [comment]
Gonna close this 'cause it could be a million things. Recommend:

- Making sure native modules (`react-native-orientation-listener`) are linked properly
- Cleaning the XCode project
- Reseting the content/settings in the simulator
- If you renamed your project, make sure you rename the Scheme as well
