### ISSUE TITLE
Can't get it running on IOS simulator

### ISSUE THREAD

**Issue by Nickman87** [tuckerconnelly/carbon-ui#7]
I'm trying to get carbon-ui to work in a react-native app so I thought (according to this page: https://carbon-ui.com/getting-started/installation) I only needed the carbon-ui library.
But after running it, I get an error asking for the 'react-native-universal' lib.
After adding that one I get an error asking for the 'react-native-web' lib.

Even after installing all of the listed dependencies, I am still getting errors. Am I missing something obvious here?

**Comment by tuckerconnelly** [comment]
Hey man, I removed all the `react-native-universal` stuff and tested on a new project. Should be good to go. Just re-run `npm -S i tuckerconnelly/carbon-ui`.

Lemme know if you're still having problems :)

**Comment by Nickman87** [comment]
I got it up and running, thanks!
