### ISSUE TITLE
Component roadmap?

### ISSUE THREAD

**Issue by hervejegou** [tuckerconnelly/carbon-ui#8]
Hello and thanks for a great library! This is how all UI for apps designed for web and mobile should/will be developed very soon.

I have a react app UI designed with [Onsen UI](https://onsen.io/v2/docs/guide/react/) which works in web and with Cordova,  but want to switch to react-native + react-native-web UI.

I have looked at [Native-base-web](https://chion82.gitbooks.io/nativebase-for-web/content/) and at carbon-ui. Carbon-ui is a better choice (though I am no expert).

I have compared carbon-ui carefully to [Native-base-web](https://chion82.gitbooks.io/nativebase-for-web/content/) and looked at what would be used for a rather simple app UI and I only see a few items/components missing in Carbon-ui to allow full UI development:

1. sample code for bottom navigation
2. list item with avatar or image in the left (now it seems we can add an element in right-icon only?)
3. right side panel (could be the navigation drawer with one added prop 'openFromRight'  to change the translateX styles values)
4. for forms: radio button / checkbox ? dropdown / select ?

I have limited experience and I tried to see if I could do this myself. At best I could maybe hack item 3 so I think I am stuck.

It would be great if you could give a component roadmap so interested users could see what to expect shortly/next and could then try to design themselves what is not on roadmap and contribute back maybe ?

Thanks again and I look forward to using carbon-ui soon.

**Comment by tuckerconnelly** [comment]
Hey man, thanks for considering carbon-ui :)

I added a basic roadmap: https://github.com/tuckerconnelly/carbon-ui/blob/master/ROADMAP.md

But basically, I'll add components as they're need in my projects. I'll also try to build anything that pops up in the issues pretty quickly.

I added an example for BottomNavigation: http://carbon-ui.com/components/BottomNavigation

Also added issues for the other things :)

**Comment by hervejegou** [comment]
Thanks for the quick update! This is looking really promising.
